server:
  port: 8185
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
    session:
      cookie:
        path: /

sysmonitor:
  sshid: jenkins
  sship: 172.50.17.205
  python: python3
  run-path: /var/lib/jenkins/system_monitor/systemState.py

batch:
  path: C:/admin/api/cli/spo.cron

spring:
  application:
    name: api
  datasource:
    mysql:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql:thin:@database-1.c2n0bpo515pa.ap-northeast-1.rds.amazonaws.com:3306:mysql
      username: admin
      password: admin1234


  session:
    store-type: redis
  cache:
    type: redis
  redis:
    host: redis-16348.c13.us-east-1-3.ec2.cloud.redislabs.com
    port: 16348
    password: qweasd12

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
  - /**
  - /v1/**
